
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB:  ${DATABASE_NAME} #or recallserver
      POSTGRES_USER:  ${DATABASE_USER} #or comon
      POSTGRES_PASSWORD:  ${DATABASE_PASSWORD} #password
    volumes:
      - npgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn django_recall_server.config.wsgi:application --bind 0.0.0.0:8000 #python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  npgdata:
